POST http://localhost:8080/users
content-type: application/json

{
	"name": "Tim",
	"email": "tim@gmail.com"
}

###

GET http://localhost:8080/users

###


POST https://cherni-api.ue.r.appspot.com/users
content-type: application/json

{
	"name": "Tim",
	"email": "tim@gmail.com"
}
